import numpy as n
a=n.array(input("Enter matrix 1.0 "))
b=n.array(input("Enter matrix 2.0 "))
print("Add matrices")
print(n.add(a,b))
print("Matrices subtraction")
print(n.subtract(a,b))
print("Matrices divide")
print(n.divide(a,b))
print("Matrices Cross Product")
print(n.multiply(a,b))
print("Matrices Dot Product")
print(n.dot(a,b))
print("Square root of all elements")
print(n.sqrt(a))
print("Sum of all elements")
print(n.sum(b))
print("Transpose of a Matrix")
print(a.T)
print("Det of Matrix")
print(n.linalg.det(a))
print("Inverse of the Matrix")
print(n.linalg.inv(a))
print("Rank of Matrix")
print(n.linalg.matrix_rank(a))
print("Power of Matrix")
print(n.linalg.matrix_power(a,3))
print("Eigen values of a Matrix")
print(n.linalg.eigvals(a))
print("Trace of a Matrix")
print(n.trace(a))
